---
- name: Make Image for EGZ MF
  hosts: web-egz
  vars:
    src_dir: /home/jenkins/jenkans/egz-mf/docker/
    dest_dir: /home/ansible/docker-projects/egz-mf/
    
  tasks:
  - name: Check exists project directory
    stat: path={{ dest_dir }}
    register: res
    
  - name: Create directory for project
    shell: mkfir -p {{ dest_dir }}
    when: not res.stat.exists

  - name: Copy files to remote servers for create Image
    copy: src={{ src_dir }} dest={{ dest_dir }}
    
  - name: Make image with GCC, Make, MC
    shell: cd {{ dest_dir }}/docker4gcc && sudo docker build -f Dockerfile-4gcc -t centos-gcc .

  - name: Make image with GCC, Make, MC
    shell: cd {{ dest_dir }}/docker4distr && sudo docker build -f Dockerfile-4distr -t egz-mf-distr .

#   - name: Shutdown docker-compose
#     shell:  docker-compose down
#     ignore_errors: yes
    
#   - name: -----> Start Docker compose
#     shell: cd {{ dest_dir }} && docker-compose up -d --build
#     register: st
    
#   - debug: var=st.stdout
  
