- name: Run Images EGZ-MF
  hosts: web-egz
  vars:
    dest_dir: /home/ansible/docker-projects/egz-mf/docker4run/
    
  tasks:
  - name: Shutdown docker-compose
    shell:  cd {{ dest_dir }} && docker-compose down && docker container prune && docker image prune
    ignore_errors: yes
    
  - name: -----> Start Docker compose
    shell: cd {{ dest_dir }} && docker-compose up --build && docker-compose run -d egz-mf
    register: st
    
  - debug: var=st.stdout
