- import_playbook: /home/jenkins/jenkans/egz-mf/ansible/project_vars.yml
- name: Run Images EGZ-MF
  hosts: web-egz
  become: yes
  vars:
    dest_dir: /home/ansible/docker-projects/egz-mf/docker4run/
    app_host_dir: /home/ansible/docker-projects/egz-mf/app
    app_docker_dir: /usr/local/nginx/html
    nginx_dir: /usr/local/nginx/sbin
    
  tasks:
  - name: Stop Docker container
    shell: docker stop `docker ps | grep $PROJECT_NAME | cut -d' ' -f1`
    
  - name: Build Docker image
    shell: cd {{ dest_dir }} && docker build -f Dockerfile.yml -t egz-mf .
  
  - name: Start Docker container
    shell: docker run --rm -d -p 8080:8080 -v {{ app_host_dir }}:{{ app_docker_dir }}:ro egz-mf /bin/bash
    
  - name: Start NGINX сервер
    shell: docker exec -it `docker ps | grep {{ project_name }} | cut -d' ' -f1` sbin/nginx 
  
#   - name: Shutdown docker-compose
#     shell:  cd {{ dest_dir }} && docker-compose down && docker container prune && docker image prune
#     ignore_errors: yes
    
#   - name: -----> Start Docker compose
#     shell: cd {{ dest_dir }} && docker-compose up --build && docker-compose run -d egz-mf
#     register: st
