- name: Run Images EGZ-MF
  hosts: web-egz
  become: yes
  vars:
    project_name: "{{ lookup('env','PROJECT_NAME') }}"
    dest_dir: /home/ansible/docker-projects/{{ project_name }}/docker4run/
    app_host_dir: /home/ansible/docker-projects/{{ project_name }}/app
    app_docker_dir: /usr/local/nginx/html
    nginx_dir: /usr/local/nginx/sbin
  
  tasks:
  - name: Stop Docker container {{ project_name }}
    shell: docker stop `docker ps | grep {{ project_name }} | cut -d' ' -f1`
    ignore_errors: true
    
  - name: Build Docker image {{ project_name }}
    shell: cd {{ dest_dir }} && docker build -f Dockerfile.yml -t {{ project_name }} .
  
  - name: Start Docker container for Project "{{ project_name }}"
    shell: docker run --rm -dt -p 8080:8080 -v {{ app_host_dir }}:{{ app_docker_dir }}:ro {{ project_name }} /bin/bash
    
  - name: Start NGINX сервер in {{ project_name }}
    shell: docker exec -dt `docker ps | grep {{ project_name }} | cut -d' ' -f1` sbin/nginx 
