- name: -----> Copy project EGZ
  hosts: web-egz

  vars:
    src_dir: /home/jenkins/git/jenkins/egz/docker-test/
    dest_dir: /home/ansible/egz-docker-test

  tasks:
  - name: ===> Copy files for create Docker image and container
    copy: src={{ src_dir }} dest={{ dest_dir }}
  
  - name: ===> Shutdown docker-compose
    shell: cd {{ dest_dir }} && docker-compose down
    ignore_errors: yes
    
  - name: ===> Start docker-compose
    shell: cd {{ dest_dir }} && docker-compose up -d
    register: st
    
  - debug: var=st.stdout
