- name: -----> Copy project EGZ
  hosts: web-egz

  vars:
    src_dir: /home/jenkins/git/jenkins/egz/docker-test/
    dest_dir: /home/ansible/egz-docker-test

  tasks:
  - name: ===> Copy DOCKER
    copy: src={{ src_dir }} dest={{ dest_dir }}
    
  - name: ===> Change current dir
    shell: cd {{ dest_dir }} && pwd
    register: cur_dir
    
  - debug: var=cur_dir.stdout
  
  - name: ===> Shutdown docker-compose
    shell: cd {{ dest_dir }} && docker-compose down
    ignore_errors: yes
    
  - name: ===> Start docker-compose
    shell: cd {{ dest_dir }} && docker-compose up -d
    register: st
    
  - debug: var=st.stdout
