version: '3.3'
services:
  web-egz-test:
    build:
      context: ./user_app
      dockerfile: Dockerfile
      args:
        buildno: 1.0
#     image: debian
    environment:
        USER: 'ansible'
    env_file:
      - ./common_env.txt
      - ./project_environment.txt
#     depends_on: 
#       - db
#     volumes:
#       - type: volume
#         source: data
#         target: /bin
#         volume:
#           nocopy: true
#       - type: bind
#         source: /lib64
#         target: /lib64
    command:
      - /bin/sh
    networks:
      - net-egz-test
    domainname: egz-test.kz
    hostname: web

#   db:
#     build:
#       context: ./db
#     image: oraclelinux
#     environment:
#       USER: 'ansible'
#     env_file:
#       ./project_environment.txt
#     ports:
#         - "1521:1521"
#     volumes:
#       - "data:/bin"
#     command:
#       - /bin/sh
#     networks:
#       - net-egz-test
#     domainname: egz-test.kz
#     hostname: db

networks:
  net-egz-test:
    driver: bridge

volumes:
  data:
