version: '3.3'
services:
  app-egz-test:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        buildno: ${buildno}
    image: app-egz-test
    environment:
      USER: 'root'
    env_file:
      - ./common_env.txt
      - ./app_env.txt
    depends_on: 
      - db-egz-test
    ports:
      - "${OPEN_PORT}:80"
    volumes:
      - type: volume
        source: common_data
        target: /data
        volume:
           nocopy: true
#       - type: bind
#         source: /lib64
#         target: /lib64
    command:
      - /bin/sh
    network_mode: bridge
    domainname: egz-test.kz
    hostname: app

  db:
     build:
       context: ./db
     image: db-egz-test
     environment:
       USER: 'root'
     env_file:
       ./common_env.txt
       ./db_env.txt
     ports:
       - "1521:1521"
     volumes:
       - "common_data:/data"
     command:
       - /bin/sh
     network_mode: bridge
     domainname: egz-test.kz
     hostname: db

#networks:
#  net-egz-test:
#    driver: bridge

volumes:
  common_data:
