FROM centos
# FROM jboss/wildfly

RUN yum -y install zip && yum -y install unzip && yum -y install mc && yum -y install java && yum -y install telnet && \
    yum -y install ntp && ln -sf /usr/share/zoneinfo/Asia/Almaty /etc/localtime
ADD wildfly.tar /usr/local/

CMD ["/bin/bash"]
