db:
  image: postgres:9.5
  environment: 
    TZ: "US/Central"
  volumes:
# На хосте есть папка ./postgess
# В докере это папка /postgres-data
    - ./postgess:/postgres-data:ro
  ports:
    - "5432:5432"
