version: '3.3'
services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
      args:
        buildno: 1
    image: egz-test:1
    environment:
        USER: 'php'
    env_file:
      - ./common_env.txt
      - ./project_environment.txt
    depends_on: 
      - busybox
    volumes:
      - type: volume
        source: my_busybox
        target: /bin
        volume:
          nocopy: true
      - type: bind
        source: /lib64
        target: /lib64
    command:
      - /bin/sh
    networks:
      - egz-network-test
    domainname: ecc.com
    hostname: php

  busybox:
    build:
      context: ./busybox
    image: busybox:1.0
    environment:
      USER: 'busybox'
    env_file:
      ./project_environment.txt
    ports:
        - "80:80"
        - "443:443"
    volumes:
      - "my_busybox:/bin"
    command:
      - /bin/sh
    networks:
      - egz-network-test
    domainname: ecc.com
    hostname: k8s-shamil

networks:
  egz-network-test:
    driver: bridge

volumes:
  my_busybox:
