version: '3.7'
services:
  isbp:
    build:
      context: ./
      dockerfile: Dockerfile.yml
      args:
        buildno: 1
    command: bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0
    tty: true
    env_file:
      - ./common.env
      - ./app.env
    ports:
      - "${ADMIN_PORT}:10000"
      - "${PROJECT_PORT}:80"
    volumes:
      - type: bind
        source: /home/ansible/docker-projects/isbp/logs
        target: /usr/local/wildfly/standalone/log
    network_mode: bridge
    domainname: isbp-test.kz
    hostname: app
