version: '3.7'
services:
  isbp:
    build:
      context: ./
      dockerfile: Dockerfile.yml
      args:
        buildno: 1
    command: ./start.bat
    tty: true
    env_file:
      - ./common.env
      - ./app.env
    ports:
      - "10000:10000"
      - "8082:80"
#     volumes:
#       - type: bind
#         source: /home/ansible/docker-projects/egz-mf/app
#         target: /usr/local/nginx/html
    network_mode: bridge
    domainname: isbp-test.kz
    hostname: app
