- name: Install software for Электронных государственных закупока, АО "ЦЭФ"
  hosts: web-egz
  become: yes
  
  tasks:
  
  - name: Install Docker
    service: name=docker state=started enabled=yes
    register: res
    
  - debug: var=res.stdout
