- name: -----> pip-install-docker for Ansible
  hosts: web-egz
  become: yes
  
  tasks:
  
  - name: ===> Install repository PIP
    shell: yum -y install epel-release 
    
  - name: ===> Install pip
    shell: yum -y install python-pip
#     check_mode: yes
    
  - name: ===> Install Docker
    shell: pip -y install docker && pip -y install 'docker-compose>=1.7.0'
    check_mode: yes
