- name: -----> pip-install-docker for Ansible
  hosts: web-egz
  become: yes
  
  tasks:
  - name: ===> Check exist pip
    stat: path=/usr/bin/pip
    register: pip_stat
    
  - block:
    - name: ===> Install repository PIP
      shell: yum install epel-release 
    
    - name: ===> Install pip
      shell: yum install python-pip 
    when: not pip_stat.stat.exists

   - name: ===> Install Docker
     shell: pip install docker && pip install 'docker-compose>=1.7.0'
     check_mode: yes
