- name: -----> pip-install-docker for Ansible
  hosts: web-egz
  become: yes
  
  tasks:
  
  - name: Install pip
    shell: yum install epel-release && yum install pip
    
  - name: Install Docker
    shell: pip install docker && pip install 'docker-compose>=1.7.0'
    check_mode: yes
