
---
- hosts: localhost
  gather_facts: no

  tasks:
#     - debug: 
#         var: "{{ prj_name }}"
        
    - name: Call playbook
      shell: /usr/bin/ansible-playbook ~/jenkans/{{ prj_name }}/ansible/prepare-image.yml
