
---
- hosts: all
  gather_facts: no

  tasks:
#     - debug: 
#         var: "{{ prj_name }}"
        
    - name: Call playbook
      shell: ansible-playbook ~/jenkans/{{ prj_name }}/ansible/prepare_image.yml
