- name: Restore HOSTS file for Ansible
  hosts: localhost
  become: yes
  
  vars:
    src_file: /home/jenkins/git/jenkins/ansible/hosts 
    dest_file: /etc/ansible/hosts
  
  tasks:
  - name: Copy HOSTS file
    copy: src={{ src_file }} dest={{ dest_file }}   
