---
- name: Make Image for EGZ MF
  hosts: web-isgp
  become: yes
  vars:
    project_name: "{{ lookup('env','PROJECT_NAME') }}" 
    src_dir: /home/jenkins/jenkans/{{ project_name }}/docker/
    dest_dir: /home/ansible/docker-projects/{{ project_name }}/
    src_wf: /home/jenkins/projects/{{ project_name }}/
 
  tasks:
  - name: Check exist (create) project directory {{ dest_dir }}
    file: 
      path: {{ dest_dir }}
      state: directory
      mode: 0755
    
  - name: Copy JENKANS files to remote servers for create Image
    copy: src={{ src_dir }} dest={{ dest_dir }}

  - name: Copy WildFly files to remote servers for add to Image
    copy: src={{ src_wf }} dest={{ dest_dir }}/app/

  - name: Make image with GCC, Make, MC
    shell: cd {{ dest_dir }}docker4wf && sudo docker build -f Dockerfile-4wf.yml --rm -t centos-wf .

#   - name: Make image with GCC and packages {{ project_name }}-pack
#     shell: cd {{ dest_dir }}docker4pack && sudo docker build -f Dockerfile-4pack.yml --rm -t {{ project_name }}-pack .

#   - name: Make Finish Image {{ project_name }}-finish
#     shell: cd {{ dest_dir }}docker4distr && sudo docker build -f Dockerfile-4distr.yml --rm -t {{ project_name }}-finish .
