- name: Open firewall ports
  hosts: web-isbp
  become: yes
  vars:
    project_port: "{{ lookup('env','PROJECT_PORT') }}" 
    admin_port: "{{ lookup('env','ADMIN_PORT') }}" 
  
  tasks:
  - name: Add open ports to firewall
    shell: firewall-cmd --permanent --add-port={{ project_port }}/tcp && firewall-cmd --permanent --add-port={{ admin_port }}/tcp

  - name: Reload firewall
    shell: firewall-cmd --reload
