- name: -----> Prepare LOCALHOST
  hosts: localhost
  become: yes
  vars:
    project_name: "{{ lookup('env','PROJECT_NAME') }}" 
    kz_zip: /home/jenkins/projects/{{ project_name }}/kz.zip
    maven_s: /home/jenkins/jenkans/{{ project_name }}/docker/docker4run/{{ project_name }}-maven.xml
    maven_gs: /home/jenkins/jenkans/{{ project_name }}/docker/docker4run/{{ project_name }}-settings.xml
  
  tasks:
  - name: Check exist .m2/repository project directory
    stat: 
      path: "/home/jenkins/.m2/repository/kz"
    register: m2_stat

  - name: Check exists isbp maven file in /etc/maven dir
    stat: 
      path: "/etc/maven/{{ project_name }}.xml"
    register: maven_stat
    
  - name: Check exists isbp maven file in /etc/maven dir
    stat: 
      path: "/etc/maven/{{ project_name }}-settings.xml"
    register: maven_stat_gs
    
  - block:
    - name: Create directory /etc/maven
      file: 
        path: /etc/maven
        state: directory
        
    - name: Copy Maven file
      copy: src={{ maven_s }} dest=/etc/maven/{{ project_name }}.xml

    - name: Copy Maven GS file
      copy: src={{ maven_gs }} dest=/etc/maven/
    when: not maven_stat.stat.exists or not maven_stat_gs.stat.exists
    
  - block:
    - name: Check ~/.m2 project directory
      file: 
        path: "~/.m2/repository/kz"
        state: directory
        
    - name: create .m2 directory
      shell: unzip -d ~/.m2/repository {{ kz_zip }} 
      when: not m2_stat.stat.exists
