---
- name: -----> Initialization Git for Application
  hosts: localhost
#   become: yes
  vars:
    project_name: "{{ lookup('env','PROJECT_NAME') }}"
    project_port: "{{ lookup('env','PROJECT_PORT') }}"
    repo: "{{ lookup('env','REPO') }}"
    repo_dir: /home/jenkins/projects/{{ project_name }}/repo
    app_dir: /home/jenkins/projects/{{ project_name }}
#     deployments_dir: /home/ansible/docker-projects/{{ project_name }}/deployments

  tasks:
  - name: Check exists Git
    stat: path="{{ repo_dir }}"
    register: stat_git

  - name: Check exists Git
    stat: path="~/.m2/repository/kz"
    register: stat_module1
    
  - block:
    - name: Create dir for mavens modules
      file: 
        path: "~/.m2/repository"
        state: directory    
        owner: jenkins
        group: jenkins
        mode: 0777
        
    - name: Unzip modules for mavens into ~/.m2/repository
      shell: unzip {{ app_dir }}/kz.zip -d ~/m2/repository      
    when: not stat_module1.stat.exists
 
  - block:
    - name: Check exist (create) project`s app directory {{ app_dir }}
      file: 
        path: "{{ repo_dir }}"
        state: directory    
        owner: jenkins
        group: jenkins
        mode: 0777

    - name: Cloning from repository {{ repository }}
      shell: cd {{ repo_dir }} && git init && git clone {{ repo }}    
    when: not stat_git.stat.exists   
    
  - name: Pulling from repository
    shell: cd {{ repo_dir }}/public_dev_isbp && git pull
    when: stat_git.stat.exists   
