---
- name: -----> Initialization Git for Application and Make and Deploying Application
  hosts: localhost
  vars:
    project_name: "{{ lookup('env','PROJECT_NAME') }}"
    repo_name: "{{ lookup('env','REPO_NAME') }}"
    repo: "{{ lookup('env','REPO') }}"
    repo_dir: "/home/jenkins/projects/{{ project_name }}/repo"
    repo_home: "{{ repo_dir }}/{{ repo_name }}"
  
  tasks:
  - name: Check exists Git
    stat: path="{{ repo_dir }}"
    register: stat_git

  - name: Check exists Git
    stat: path="~/.m2/repository/kz"
    register: stat_module1
    
  - block:
    - name: Create dir for mavens modules
      file: 
        path: "~/.m2/repository"
        state: directory    
        owner: jenkins
        group: jenkins
        mode: 0777
        
    - name: Unzip modules for mavens into ~/.m2/repository
      shell: unzip {{ app_dir }}/kz.zip -d ~/.m2/repository      
    when: not stat_module1.stat.exists
 
  - block:
    - name: Check exist (create) project`s app directory {{ app_dir }}
      file: 
        path: "{{ repo_dir }}"
        state: directory    
        owner: jenkins
        group: jenkins
        mode: 0777

    - name: Cloning from repository {{ repository }}
      shell: cd {{ repo_dir }} && git init && git clone {{ repo }}    
      when: not stat_git.stat.exists   
    
  - name: Pulling from repository
    shell: cd {{ repo_home }} && git pull
    when: stat_git.stat.exists   

  - name: Deploying ISBP module to 149 with Maven
    shell: mvn -f {{ repo_home }}/isbp/pom.xml -s /etc/maven/{{ project_name }}.xml -gs /etc/maven/{{ project_name }}-settings.xml wildfly:deploy -Pdocker149
  - name: Deploying ISBP module to 151 with Maven
    shell: mvn -f {{ repo_home }}/isbp/pom.xml -s /etc/maven/{{ project_name }}.xml -gs /etc/maven/{{ project_name }}-settings.xml wildfly:deploy -Pdocker151
    
  - name: Deploying ISBP-ADMIN module to 149 with Maven
    shell: mvn -f {{ repo_home }}/isbp-admin/pom.xml -s /etc/maven/{{ project_name }}.xml -gs /etc/maven/{{ project_name }}-settings.xml wildfly:deploy -Pdocker149
  - name: Deploying ISBP-ADMIN module to 151 with Maven
    shell: mvn -f {{ repo_home }}/isbp-admin/pom.xml -s /etc/maven/{{ project_name }}.xml -gs /etc/maven/{{ project_name }}-settings.xml wildfly:deploy -Pdocker151

  - name: Deploying ISBP-BALANCE module to 149 with Maven
    shell: mvn -f {{ repo_home }}/isbp-balance/pom.xml -s /etc/maven/{{ project_name }}.xml -gs /etc/maven/{{ project_name }}-settings.xml wildfly:deploy -Pdocker149
  - name: Deploying ISBP-BALANCE module to 151 with Maven
    shell: mvn -f {{ repo_home }}/isbp-balance/pom.xml -s /etc/maven/{{ project_name }}.xml -gs /etc/maven/{{ project_name }}-settings.xml wildfly:deploy -Pdocker151

  - name: Deploying ISBP-BALANCE module to 149 with Maven
    shell: mvn -f {{ repo_home }}/isbp-balance/pom.xml -s /etc/maven/{{ project_name }}.xml -gs /etc/maven/{{ project_name }}-settings.xml wildfly:deploy -Pdocker149
  - name: Deploying ISBP-BALANCE module to 151 with Maven
    shell: mvn -f {{ repo_home }}/isbp-balance/pom.xml -s /etc/maven/{{ project_name }}.xml -gs /etc/maven/{{ project_name }}-settings.xml wildfly:deploy -Pdocker151

  - name: Deploying ISBP-LIMITS module to 149 with Maven
    shell: mvn -f {{ repo_home }}/isbp-limits/pom.xml -s /etc/maven/{{ project_name }}.xml -gs /etc/maven/{{ project_name }}-settings.xml wildfly:deploy -Pdocker149
  - name: Deploying ISBP-LIMITS module to 151 with Maven
    shell: mvn -f {{ repo_home }}/isbp-limits/pom.xml -s /etc/maven/{{ project_name }}.xml -gs /etc/maven/{{ project_name }}-settings.xml wildfly:deploy -Pdocker151

  - name: Deploying ISBP-PP module to 149 with Maven
    shell: mvn -f {{ repo_home }}/isbp-pp/pom.xml -s /etc/maven/{{ project_name }}.xml -gs /etc/maven/{{ project_name }}-settings.xml wildfly:deploy -Pdocker149
  - name: Deploying ISBP-PP module to 151 with Maven
    shell: mvn -f {{ repo_home }}/isbp-pp/pom.xml -s /etc/maven/{{ project_name }}.xml -gs /etc/maven/{{ project_name }}-settings.xml wildfly:deploy -Pdocker151

  - name: Deploying ISBP-RBK module to 149 with Maven
    shell: mvn -f {{ repo_home }}/isbp-rbk/pom.xml -s /etc/maven/{{ project_name }}.xml -gs /etc/maven/{{ project_name }}-settings.xml wildfly:deploy -Pdocker149
  - name: Deploying ISBP-RBK module to 151 with Maven
    shell: mvn -f {{ repo_home }}/isbp-rbk/pom.xml -s /etc/maven/{{ project_name }}.xml -gs /etc/maven/{{ project_name }}-settings.xml wildfly:deploy -Pdocker151

  - name: Deploying ISBP-STAFF module to 149 with Maven
    shell: mvn -f {{ repo_home }}/isbp-staff/pom.xml -s /etc/maven/{{ project_name }}.xml -gs /etc/maven/{{ project_name }}-settings.xml wildfly:deploy -Pdocker149
  - name: Deploying ISBP-STAFF module to 151 with Maven
    shell: mvn -f {{ repo_home }}/isbp-staff/pom.xml -s /etc/maven/{{ project_name }}.xml -gs /etc/maven/{{ project_name }}-settings.xml wildfly:deploy -Pdocker151

  - name: Deploying ISBP-LAUNCHER module to 149 with Maven
    shell: mvn -f {{ repo_home }}/task-launcher/pom.xml -s /etc/maven/{{ project_name }}.xml -gs /etc/maven/{{ project_name }}-settings.xml wildfly:deploy -Pdocker149
  - name: Deploying ISBP-LAUNCHER module to 151 with Maven
    shell: mvn -f {{ repo_home }}/task-launcher/pom.xml -s /etc/maven/{{ project_name }}.xml -gs /etc/maven/{{ project_name }}-settings.xml wildfly:deploy -Pdocker151
    
