---
- name: -----> Initialization Git for Application
  hosts: localhost
  become: yes
  vars:
    project_name: "{{ lookup('env','PROJECT_NAME') }}"
    project_port: "{{ lookup('env','PROJECT_PORT') }}"
    app_dir: /home/jenkins/projects/{{ project_name }}
    deployments_dir: /home/ansible/docker-projects/{{ project_name }}/deployments

  tasks:
  - name: Check exists Git
    stat: path="{{ app_dir }}"
    register: stat_git
    
  - name: Check exist (create) project`s app directory {{ app_dir }}
    file: 
      path: "{{ app_dir }}"
      state: directory    

  - name: Check exist (create) project`s deployments directory {{ deployments_dir }}
    hosts: web-isbp
    file: 
      path: "{{ deployments_dir }}"
      state: directory    
      
  - name: Cloning from repository
    git:
      repo: 'http://repository.ecc.kz/isgp/public_dev_isbp.git'
      dest: {{ app_dir }}
    when: not stat_git.stat.exists   

  - name: Pulling from repository
    shell: cd {{ app_dir }} && git pull &&  git config --list
    when: stat_git.stat.exists   
       
#   - name: Stopping service {{ project_name }}
#     shell: cd {{ home_dir }} && docker-compose stop {{ project_name }}   

#   - name: Starting docker-compose
#     shell: cd {{ home_dir }} && docker-compose up -d --build
    
#   - name: Starting service {{ project_name }}
#     shell: cd {{ home_dir }} && docker-compose start {{ project_name }}

  
